In [13]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [3]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [4]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [5]:
# 값의 범위를 0~1 사이로 조정하기 위해 255로 나눔 (데이터가 0~255까지의 값으로 되어있음)
train_images = train_images / 255.0
test_images = test_images / 255.0

In [6]:
# 모델 구성
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),     # flatten을 사용, 2차원 배열을 1차원 배열 값으로 변경
    keras.layers.Dense(128, activation='relu'),     # relu 활성화 함수 사용. 128개의 노드를 가진 신경망 층
    keras.layers.Dense(10, activation='softmax')    # 10개의 레이블 값을 가진 output layer, softmax로 확률로 변경함
])

In [7]:
# 모델 컴파일
model.compile(optimizer='adam',
            loss = 'sparse_categorical_crossentropy',
            metrics = ['accuracy'])         # 옵티마이저, 손실함수 설정, 지표는 정확도

In [8]:
# 데이터 훈련. 5번 반복 학습
model.fit(train_images, train_labels, epochs=5)     # verbose 기본값 1이구나

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4967 - accuracy: 0.8276: 0s - loss: 0.5211 - accuracy: 0.81 - ETA: 0s - loss: 0.518
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3732 - accuracy: 0.8661: 0s - loss: 0.3
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3354 - accuracy: 0.8777
Epoch 4/5
1875/1875 [==============================] - 2s 969us/step - loss: 0.3121 - accuracy: 0.8855
Epoch 5/5
1875/1875 [==============================] - 2s 887us/step - loss: 0.2943 - accuracy: 0.8922


In [9]:
# 테스트 데이터셋으로 모델 평가
test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)
print('\ntest accuracy:', test_acc)

313/313 - 0s - loss: 0.3756 - accuracy: 0.8662 - 306ms/epoch - 977us/step

test accuracy: 0.8661999702453613


In [11]:
# 분류 예측
predictions = model.predict(test_images)
print(predictions[0])
print(class_names[test_labels[0]], '=>', class_names[np.argmax(predictions[0])])

# 0번째 데이터의 레이블별 예측 결과와 실제데이터를 예측한 데이터 호출
# predictions에는 해당 데이터의 모든 레이블값의 확률을 출력하기 때문에 argmax를 사용, 가장 높은 값의 index 값 리턴

[1.1762748e-04 5.3678986e-07 1.0119448e-06 9.6853272e-09 4.5647874e-07
 3.1582996e-02 7.0345304e-05 4.9693339e-02 1.8725099e-05 9.1851497e-01]
Ankle boot => Ankle boot


In [12]:
# 100개의 데이터를 불러와 예측도 확인
for i in range(0, 100):
    print(class_names[test_labels[i]], '=>', class_names[np.argmax(predictions[i])])

Ankle boot => Ankle boot
Pullover => Pullover
Trouser => Trouser
Trouser => Trouser
Shirt => Shirt
Trouser => Trouser
Coat => Coat
Shirt => Shirt
Sandal => Sandal
Sneaker => Sneaker
Coat => Coat
Sandal => Sandal
Sneaker => Sandal
Dress => Dress
Coat => Coat
Trouser => Trouser
Pullover => Pullover
Coat => Pullover
Bag => Bag
T-shirt/top => T-shirt/top
Pullover => Pullover
Sandal => Sandal
Sneaker => Sneaker
Ankle boot => Sandal
Trouser => Trouser
Coat => Pullover
Shirt => Shirt
T-shirt/top => T-shirt/top
Ankle boot => Ankle boot
Dress => Coat
Bag => Bag
Bag => Bag
Dress => Dress
Dress => Dress
Bag => Bag
T-shirt/top => T-shirt/top
Sneaker => Sneaker
Sandal => Sandal
Sneaker => Sneaker
Ankle boot => Ankle boot
Shirt => T-shirt/top
Trouser => Trouser
Dress => Shirt
Sneaker => Sneaker
Shirt => Shirt
Sneaker => Sneaker
Pullover => Pullover
Trouser => Trouser
Pullover => Pullover
Pullover => Shirt
Coat => Coat
Coat => Pullover
Sandal => Sandal
Bag => Shirt
Pullover => Pullover
Pullover => Pu

# 다시!
- https://needjarvis.tistory.com/566?category=759188

In [21]:
epochs = 200        # 몇 번(혹은 얼마나 길게) 학습을 수행할 것인가
batch_size = 128    # 한 번에 입력해야 할 표본 수
verbose = 1         # 0=silent, 1=progress bar, 2=one line per epoch
validation_split = 0.2      # 훈련 프로세스 유효성 확인을 위해 남겨운 데이터
output_class = 10           # 최종 출력되는 값의 범위 지정. mnist에서는 0~9 사이라 10이 고정값

In [15]:
mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

print(X_train.shape)
print(X_test.shape)

11501568/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(10000, 28, 28)


In [18]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

X_train /= 255
X_test /= 255

> One-Hot Encoding

In [22]:
Y_train = tf.keras.utils.to_categorical(Y_train, output_class)
Y_test = tf.keras.utils.to_categorical(Y_test, output_class)
print(Y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


### 모델 생성

In [24]:
model = tf.keras.models.Sequential()
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),     # 데이터를 1차원 배열값으로 바꿔줘야 함 reshape 써도 됨
    keras.layers.Dense(128, activation='relu'),     # Dense > 레이어 생성. 128은 히든노드, activation은 활성화 함수 지정
    keras.layers.Dense(10, activation='softmax')
])