In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

str = '저는 몬스터 에너지를 좋아합니다. 그 중 몬스터 파이프라인 펀치는 너무 맛나요'

In [2]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([str])
print(tokenizer.word_index)

{'몬스터': 1, '저는': 2, '에너지를': 3, '좋아합니다': 4, '그': 5, '중': 6, '파이프라인': 7, '펀치는': 8, '너무': 9, '맛나요': 10}


In [5]:
encoded = tokenizer.texts_to_sequences([str])[0]
print(encoded)

[2, 1, 3, 4, 5, 6, 1, 7, 8, 9, 10]


In [6]:
onehot = tf.keras.utils.to_categorical(encoded)
print(onehot)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
